### ISSUE TITLE
Not working on portable devices

### ISSUE THREAD

**Issue by flamenco108** [regebro/hovercraft#100]
Hello.

I don't need to link to [my page](http://stenotypia.pl), as there is enough to check it on the [demo page](http://regebro.github.com/hovercraft). Is there any switch (to switch on) to make the presentation usable on portable (I mean: tablets, smartphones etc.) devices's browsers? **If not - that's an issue.**

I checked it on several Android devices, on Chrome, Firefox and built-in browser (Safari???). There is a box with an instruction of buttons to push to move the slides, but perhaps it should show some kind of "next", "previous" buttons?

**Comment by regebro** [comment]
No, that would defeat the purpose, but it should be possible to hook it up to swipe events.

**Comment by regebro** [comment]
It works on firefox, but at least on my phone it's enormously slow. impress.js doesn't seem to work on mobile chrome. I don't think this is a useful way of running. I'm investigating a special presenter console for mobile phones though, would that solve your usecase?

**Comment by flamenco108** [comment]
I don't know, what is the special presenter console ;)
I had to resign of using it as the most of any notifications from users was about this problem. I assumed, that they want to see this webpage on mobile devices.

**Comment by regebro** [comment]
OK, that's not going to help then.

**Comment by frederikmoellers** [comment]
I've implemented touch controls in my [custom hovercraft template](https://github.com/frederikmoellers/hovercraft-template), but you need to "request desktop version" in the mobile browser (tested with chrome) for them to work.
I did however manage to bind swipe events to the next()/prev() functions of impress.js. Unfortunately, you have to disable the regular click-to-go-to-a-slide function because the touch and click events interfere with each other.

**Comment by frederikmoellers** [comment]
The issue seems to be resolved for Chrome on Android, maybe due to updates of Chrome and/or impress.js. I tried both one of my presentations and the demo page. You do have to explicitly "Request [the] Desktop Version" in the context menu, but it works perfectly fine using swipe gestures afterwards.

If anyone can help me debug why Chrome ignores some CSS if you don't request the Desktop version, I can try to fix this as well.

**Comment by regebro** [comment]
Cool!

**Comment by frederikmoellers** [comment]
FYI: I think I found out why it doesn't work immediately. It's a bug in impress.js which lets impress.js think that it is not supported in this browser. The `<body>` tag will be rendered as `<body class="impress-not-supported impress-not-supported ">`. I'll see if there's a way to fix it in impress.js (upstream) and if not, if we can somehow fix it in hovercraft.

**Comment by frederikmoellers** [comment]
Sorry for the spam, I should do more research before commenting.
impress.js [doesn't support mobile browsers and the maintainers will probably not change this in the near future](https://github.com/impress/impress.js/issues/282).
If hovercraft users **really** want to support mobile browsers, I think we can put an option into hovercraft to "hack" impress' mobile browser detection and force it to support mobile devices. I'll try to come up with something. 

Presentation authors have to keep in mind, though, that some presentations might be too much for (especially older) devices and can potentially crash the browser. Also, not all features might work equally well on all devices. That's pretty much the gist of the whole discussion in the impress.js issue and the reason why it's still not supported there.

**Comment by regebro** [comment]
What I mostly want for mobile is a mobile presenter console, perhaps a separate one from the normal presenter console, maybe not, so you can have your notes on the phone, and control the presentation from it.

I've been investigating it on the https://github.com/regebro/hovercraft/tree/asyncio branch, but I only have time here and there.

**Comment by ccamara** [comment]
From [impress.js 1.0.0 relase notes ](https://github.com/impress/impress.js/releases/tag/1.0.0), it has a new feature (amongst others) that

> Removes the code that prevented impress.js from running on mobile phones

I have created a PR #170  that is an attempt to use impress.js 1.0.0 vs the old 0.6.0 that hovercraft is currently using. Please review it and use it if you need that feature.

**Comment by yeyeto2788** [comment]
@frederikmoellers, @flamenco108 can you guys give us an update on this, so we can close this issue? From what I can see PR #170 add this improvement.

**Comment by frederikmoellers** [comment]
I quickly tested some slides on a mobile device and it seems to work reasonably well with impress.js 1.0. IMHO we can close the issue as @flamenco108's main request is satisfied by impress.js 1.0. @regebro's idea of a mobile presenter console is not implemented as far as I can see, but that is arguably another issue.

**Comment by regebro** [comment]
Thanks!
