### ISSUE TITLE
FAIL: test_big (hovercraft.tests.test_hovercraft.HTMLTests)

### ISSUE THREAD

**Issue by danstender** [regebro/hovercraft#102]
Hi Lennart,
continuous integration on Debian now came up with a failure:
https://bugs.debian.org/813159 (build log attached)
Greetings,
DS

**Comment by regebro** [comment]
That's a difference in the code highlighting, which is done by Pygment. So somehow Pygment ends up doing different things in this case, perhaps you are using a custom version with changes?

I think the way forward there is to make the tests less brittle by not requiring the output to be exactly the same, but this will be a bit of work.

**Comment by danstender** [comment]
Thanks for the pointer to Pygments. AAMOF the test crash on amd64 runs against
2.1+dfsg-1 while the armhf test build runs through with 2.0.1+dfsg-1.1, so there is
some difference. I'll get deeper into it ...
