### ISSUE TITLE
Install is not working on Ubuntu (Xenial version)

### ISSUE THREAD

**Issue by melodie11** [regebro/hovercraft#105]
Hello,

This is what I tried, following your simple pip3 install instruction: http://pastebin.fr/46123

My guess is that further instruction would be needed?

**Comment by regebro** [comment]
The missing part is probably this: `sudo apt-get install libxslt-dev libxml2-dev`

Maybe you need python3-dev as well (but I didn't need it when I tried).

I should really sit down and learn how to make Ubuntu packages.

**Comment by melodie11** [comment]
Thanks! Meanwhile, I have been told the package is in Debian testing and sid, so using myself the dev version of Ubuntu (next 16.04) I have been able to install it using the package manager. (If you have a discussion somewhere where it would be relevant to talk about the user documentation, if you are willing to, just let me know?)

Best regards,
Mélodie

**Comment by regebro** [comment]
The problem is that the instructions are different on every platform, so it gets hard to maintain. 

Good that the debian package works!
