### ISSUE TITLE
Cookiecutter template

### ISSUE THREAD

**Issue by jhermann** [regebro/hovercraft#106]
I made a template for Hovercraft! projects, you might want to link it in the docs somewhere…

https://github.com/Springerle/hovercraft-slides

**Comment by regebro** [comment]
Thanks, that's cool. It's very complex and includes everything and the kitchen sink, as is tradition with Cookiecutter templates, so I think I won't link to it, I worry that it will scare people away as you have to learn a whole lot of extra things to use it.
