### ISSUE TITLE
Support for Fragments

### ISSUE THREAD

**Issue by jullit31** [regebro/hovercraft#113]
Are there any plans to support fragments, maybe similar to [flowtime.js](http://marcolago.github.io/flowtime.js/#/section-3/page-1)?

**Comment by regebro** [comment]
Not at the moment, no. You can get similar effects by hiding slides that hasn't been shown yet with CSS, and then just moving the position slightly down for each slide. New lines will then appear gradually.

**Comment by Spheerys** [comment]
+1 for the fragment support :)

**Comment by regebro** [comment]
I've been thinking more about this, and the only way I can see this being done is by having one slide per fragment. Possibly something could be added to impress.js itself, but Hovercraft can't do it by itself.

**Comment by jullit31** [comment]
@regebro I don't know whether this helps, but by now there is an [active fork](https://github.com/impress/impress.js/issues/81#issuecomment-294599107) of impress.js that supports fragments.
