### ISSUE TITLE
Customize the impressConsole

### ISSUE THREAD

**Issue by warsaw** [regebro/hovercraft#115]
I want to customize the impressConsole, mostly to make some of the windows bigger.  They are generally too small for me to read.  I know what css I need to change, but I can't figure out a way to get hovercraft to vend my changes when the console is opened.

I've tried using the `:css:` tag in the presentation, adding the `--css` flag on the command line, and various other tricks, none of which seem to work for the console.  Is there any way I can customize the console?

**Comment by warsaw** [comment]
Short of forking the code of course :)

**Comment by regebro** [comment]
There's no way to add css for the console. I'll add that as a feature request.
