### ISSUE TITLE
Using Emojis in titles fails to build

### ISSUE THREAD

**Issue by freddymartinez9** [regebro/hovercraft#119]
Every time I attempt to put an emoji in a title, the presentation will fail to build with "title too short". I suspected the space between the r and the emoji were to blame but I tried various combinations of spacing and none worked. 

```
Danger⚠️
=======
```

**Comment by regebro** [comment]
That's not an emoji, I would think that it's a unicode character. And very trickily, they are actually 1-4 bytes long. This specific one is two bytes long, so this works:

`Danger⚠️
========`

**Comment by freddymartinez9** [comment]
That absolutely worked!
