### ISSUE TITLE
Latex expressions are not converted in the html file

### ISSUE THREAD

**Issue by fsdias** [regebro/hovercraft#123]
EDITED:

Latex expressions inserted as below are not rendered to html.

.. math::
    \hat{p} = \frac{1}{w} \int_0^w g(y; \boldsymbol{\hat{\theta}}) \text{d}y

I just realized that impress.js does not have support for this and therefore hovercraft doesn't either. It would be useful to add support for this with mathjax [1] or katex [2] for instance.

[1] https://www.mathjax.org/
[2] https://khan.github.io/KaTeX/

**Comment by frederikmoellers** [comment]
Support for MathJax has been introduced with 0def2ac.

**Comment by fsdias** [comment]
Thanks!
