### ISSUE TITLE
cdn.mathjax.org end-of-life

### ISSUE THREAD

**Issue by pkra** [regebro/hovercraft#124]
cdn.mathjax.org is nearing its end-of-life. Please check https://mathjax.org/cdn-shutting-down for migration tips.

**Comment by regebro** [comment]
Yeah, I saw, it means mathjax users need to use the --mathjax parameter to point to MathJax. We should also change this to use a local copy, one that preferably gets copied to the presentation destination, which requires some work.

**Comment by regebro** [comment]
Ugh. A local copy is 34.000 files, and over 1300 directories. I don't want to ship that with Hovercraft. I also don't really feel like keeping it updated.

I'm currently leaning towards not having a default to the MathJax parameter, and requiring it, and any MathJax user has to deal with this him/herself.

**Comment by regebro** [comment]
I implemented it so that if you point at a local copy of MathJax it will be copied in to the presentation for a nice standalone experience. All 34.000 files.
