### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by MCSH** [regebro/hovercraft#128]
Hello

I think I saw this somewhere now I can't find it. Is there a way to provide an offline version of the documentation? I'd like to use it in class but I need to provide something that would work without installing anything on user's computer.

With a normal impressjs I would provide the HTML with the relevant JS, is there a shortcut of doing that in hovercraft?

Something like an extra flag (--save for example)

Thanks.

**Comment by frederikmoellers** [comment]
If you pass a directory to hovercraft as the last command-line parameter, it will save the presentation in that directory. You can then open the HTML file (index.html) on any computer which has a web browser without the need for additional software.

**Comment by regebro** [comment]
The examples are of course to be rended by Hovercraft! but then documentation is made for [Sphinx](http://www.sphinx-doc.org/en/stable/). You can install it and generate offline docs with the make file, but easier is to download them from https://hovercraft.readthedocs.io/ . Click the "ReadTheDocs" link in the lower left corner.
