### ISSUE TITLE
Raw html doesn't work

### ISSUE THREAD

**Issue by sw1sh** [regebro/hovercraft#130]
OSX with new python 3.4 conda environment. 

```
pip install hovercraft
```

Make `test.rst` file with contents:

```
----

.. raw:: html

  <p>Text</p>
```

Run `hovercraft test.rst` and go to `http://localhost:8000/`.

It still outputs escaped `&lt;p&gt;Text&lt;/p&gt;` on the page.

<img width="194" alt="screen shot 2017-05-11 at 13 47 50" src="https://cloud.githubusercontent.com/assets/1057888/25945712/9cab8f36-3650-11e7-87ae-eda70ef2eb12.png">

**Comment by regebro** [comment]
That works for me, it inserts it as HTML into the page.

![works](https://cloud.githubusercontent.com/assets/820596/25943465/38ac85d6-3640-11e7-969c-1825827e1377.png)

**Comment by sw1sh** [comment]
@regebro What can I do wrong here then, any idea?

**Comment by regebro** [comment]
No idea. Do you get any error messages when generating the presentation?
If not can you upload the presentation as an attachment?

**Comment by sw1sh** [comment]
@regebro No errors or warnings. I've discribed the minimal steps to reproduce this.

**Comment by regebro** [comment]
Strange.

![screenshot from 2017-05-11 13-17-50](https://cloud.githubusercontent.com/assets/820596/25946623/4817e018-364c-11e7-8fe3-5cf40534696d.png)

This is the HTML output I get:

[index.txt](https://github.com/regebro/hovercraft/files/992791/index.txt)

**Comment by sw1sh** [comment]
Can you run this script?

```
import docutils
from docutils.core import publish_string
from docutils.writers.docutils_xml import Writer

text = '''
.. raw:: html

   <p>Text</p>
'''

print(publish_string(text, writer=Writer()))
```

I'm getting:

`b'<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE document PUBLIC "+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML" "http://docutils.sourceforge.net/docs/ref/docutils.dtd">\n<!-- Generated by Docutils 0.13.1 -->\n<document source="&lt;string&gt;"><raw format="html" xml:space="preserve">&lt;p&gt;Text&lt;/p&gt;</raw></document>'`

That's what the `rst2xml` function from `hovercraft.parse` basically does. Do you get unescaped output with it?

**Comment by regebro** [comment]
Yeah, but that's how it should be. That's an XML file, where one field is HTML. It's escaped, because otherwise it would be a part of the XML, and it isn't.

The XSL template that then generates the HTML output has this in it:

`<xsl:template match="raw[@format='html']">
	<xsl:value-of select="." disable-output-escaping="yes" />
</xsl:template>
`

This sticks the HTML code straight into the HTML, unescaped.

**Comment by sw1sh** [comment]
@regebro Yeah, right. But seems like that XSL template doesn't work for me for some reason.

**Comment by regebro** [comment]
Hm. A version mismatch somewhere?

lxml 3.7.3
libxslt 1.1.28
libxml2 2.9.3

Ubuntu 16.04

**Comment by sw1sh** [comment]
Indeed, I run on Mac with

lxml-3.6.4
libxslt-1.1.28
libxml2-2.9.4

I'll try to install an earlier `lxml` then, hopefully it would help...

**Comment by sw1sh** [comment]
No, installing `lxml-3.7.3` didn't fix it. It seems tricky to downgrade `libxml2`, but I doubt that would help anyway.

**Comment by regebro** [comment]
No, if it was different versions on libxslt possibly.
No, I really can't think of a reason for this behavior,

**Comment by sw1sh** [comment]
It looks like `html.tostring` is acting pretty weird. What do you get with this?

```
import docutils
from docutils.core import publish_string
from docutils.writers.docutils_xml import Writer

from lxml import etree, html

text = '''
Begin 

.. raw:: html

   <p>Unescaped Text</p>


<p>Escaped Text</p>

End
'''

xml = publish_string(text, writer=Writer())
tree = etree.fromstring(xml)

parser = etree.XMLParser()

xsl = open('hovercraft/templates/reST.xsl').read()

xsl_tree = etree.fromstring(xsl, parser)
transformer = etree.XSLT(xsl_tree)
tree = transformer(tree)
result = html.tostring(tree)

print(bytes(tree))

print(result)
```

For me it outputs

```
b'<?xml version="1.0"?>\n<p xmlns="http://www.w3.org/1999/xhtml">Begin</p><div>Unescaped Text</div><p xmlns="http://www.w3.org/1999/xhtml">&lt;div&gt;Escaped Text&lt;/div&gt;</p><p xmlns="http://www.w3.org/1999/xhtml">End</p>\n'
b'<p xmlns="http://www.w3.org/1999/xhtml">Begin</p>&lt;div&gt;Unescaped Text&lt;/div&gt;'
```

**Comment by regebro** [comment]
I get

```TypeError: 'lxml.etree._Element' object cannot be interpreted as an integer```

on `print(bytes(tree))`

**Comment by regebro** [comment]
No ignore the deleted message, I had a previous error I didn't see.

```b'<?xml version="1.0"?>\n<p xmlns="http://www.w3.org/1999/xhtml">Begin</p><p>Unescaped Text</p><p xmlns="http://www.w3.org/1999/xhtml">&lt;p&gt;Escaped Text&lt;/p&gt;</p><p xmlns="http://www.w3.org/1999/xhtml">End</p>\n'

b'<p xmlns="http://www.w3.org/1999/xhtml">Begin</p><p>Unescaped Text</p>```

**Comment by sw1sh** [comment]
So, it indeed something wrong with `lxml`, but our versions match. Therefore it should be some system library related then...

**Comment by regebro** [comment]
Yeah, very strange.

**Comment by sw1sh** [comment]
I've fixed it! 
Just did some `brew` magic with uninstalling, installing, unlinking, linking of `libxslt` and `libxml2` and it fixed itself.😅

**Comment by regebro** [comment]
![](https://media.tenor.co/images/dd6b9d90eb85a6aaa3ad680960ffccc1/tenor.gif)
