### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by berserk82** [regebro/hovercraft#131]
Does HoverCraft require anything but a webserver to run (and edit presentations)? (eg. node, frameworks, etc)

**Comment by regebro** [comment]
It doesn't even require a webserver, it includes one. 

It can also generate the presentation to a directory and you can load it from a browser with File -> Open and no server is used at all. However, some browsers require special settings to open the presenter console in that case, so the webserver is easier to use.

**Comment by berserk82** [comment]
But what if I want to use it without Python?

**Comment by regebro** [comment]
What is your *actual* question? What are you trying to do?

**Comment by berserk82** [comment]
I would like to run HoverCraft locally on my web server, which is Apache, and anyhow I would like to use just HTML/CSS/JavaScript, and eventually PHP.

**Comment by regebro** [comment]
What does "run" mean?

Hovercraft is a Python program. You need Python to run it. It generates HTML/JS/CSS presentations. You need a browser to show them.

**Comment by berserk82** [comment]
Ah, ok. I thought it were a browser app.

**Comment by regebro** [comment]
No, the generated presentation is a browser app.

The documentation is here: https://hovercraft.readthedocs.io/en/latest/

You can easily install Hovercraft! and try this yourself if the documentation isn't clear enough and it should quickly clear up.

**Comment by berserk82** [comment]
Thanks anyhow. Are you aware of a similar project that is a web app?

**Comment by regebro** [comment]
Searching for "open source prezi" finds some that might fit.

**Comment by berserk82** [comment]
Thanks so much.
