### ISSUE TITLE
[Documentation] Dead link

### ISSUE THREAD

**Issue by lcetinsoy** [regebro/hovercraft#135]
Hi ! 

I am discovering Hovercraft which seems very nice. The example links in the examples section of http://hovercraft.readthedocs.io/en/latest/presentations.html are dead

**Comment by yeyeto2788** [comment]
@lcetinsoy, @ReblochonMasque this seems to be fixed already on https://github.com/regebro/hovercraft/pull/148 and on the https://hovercraft.readthedocs.io/en/latest/presentations.html page they are working. Can we close this issue in order to get a cleaner backlog?

**Comment by lcetinsoy** [comment]
sure !
