### ISSUE TITLE
example exercising static header/footer?

### ISSUE THREAD

**Issue by smxzehvb** [regebro/hovercraft#136]
The documentation notes that static headers and footers are now supported; however, there does not seem to be a workable example of using headers or footers in any of the example presentations. I've tried to include them with the commands shown [here](https://hovercraft.readthedocs.io/en/latest/presentations.html#styling-your-presentation), but no header/footer are generated in the html. 
Thanks

**Comment by regebro** [comment]
OK, I added this to the tutorial.rst so there is an example.

Also, this requires Hovercraft 2.4, which isn't released yet, so I'm releasing it soon. It has tons of new features and may be buggy.

**Comment by smxzehvb** [comment]
Thanks very much! Look forward to the new release.
