### ISSUE TITLE
Ran into two bugs in the parser.

### ISSUE THREAD

**Issue by cschwenz** [regebro/hovercraft#138]
First parser bug:

```
    ***test***
```
generates
```
    <strong>*test*</strong>
```
instead of the expected
```
    <strong><em>test</em></strong>
```

---

Second parser bug:

```
    ``command``s
```
generates the error
```
    (WARNING/2) Inline literal start-string without end-string.
```
instead of the expected
```
    <tt>command</tt>s
```

**Comment by regebro** [comment]
`*text*` is emphasis, and `**text**` is strong emphasis. `***text***` isn't supported in reStructuredText.

I would have expected `
``command``s
` to work, but it doesn't, I don't know if that's a bug in docutils reStructuredText implementation or a limitation of restructuredText itself.
