### ISSUE TITLE
Manual install instructions / offline install / behind a proxy

### ISSUE THREAD

**Issue by cjohnsonuk** [regebro/hovercraft#149]
I'm trying to install on windows
I'm behind a proxy that requires authentication

When I run 

pip3 install hovercraft

or download hovercraft, unzip, change into the directory and run

pip3 install -e ./

I get this: 

Collecting docutils>=0.9 (from hovercraft==2.5.dev0)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',))': /simple/docutils/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',))': /simple/docutils/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',))': /simple/docutils/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',))': /simple/docutils/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',))': /simple/docutils/
  Could not find a version that satisfies the requirement docutils>=0.9 (from hovercraft==2.5.dev0) (from versions: )
No matching distribution found for docutils>=0.9 (from hovercraft==2.5.dev0)

Is it a non trivial task to do a manual installation that will work offline?

**Comment by regebro** [comment]
Making installers in general is a non-trivial task, yes. I haven't looked into making Windows distributions, and I don't think I will have time in the immediate future.

However, you could try to run pip --download on another windows machine that *is* connected to the internet. See here:

https://pip.pypa.io/en/stable/reference/pip_download/

**Comment by regebro** [comment]
Closing from lack of feedback. I'm assuming it works.
