### ISSUE TITLE
Feature request: support for substeps

### ISSUE THREAD

**Issue by mmlanger** [regebro/hovercraft#153]
Hey!
First of all:
I really like this project as it actually makes impress.js accessible without the trouble of directly messing with html. As I really like to use this project for my scientific presentations I'd need the possibilty to do substeps, which seems to not be supported by hovercraft as far as I can tell.

Recently, support for substeps was merged to impress.js:
https://github.com/impress/impress.js/commit/156da0bb3f9a2d77f9a7b851fe4c39ef443340c3

Could we have this for hovercraft? And if so, maybe have an example for this?

**Comment by regebro** [comment]
Yeah, since each substep just has a class this should be doable. It won't be pretty though:

```
.. class:: substep

This is a substep.

.. class:: substep

And so is this.

```

I'll think about ways of implementing this in a nicer way.

**Comment by regebro** [comment]
It's not implemented yet.

**Comment by pappasam** [comment]
@srhuels with the lastest version, the following code works for substeps (you need to write html):

```restructuredtext
Fruits
======

.. raw:: html

    <p class="substep">Orange</p>
    <p class="substep">Apple</p>

----

Goodbye
=======

Done
```

@regebro I'll think about how to update the parser a bit more elegantly and submit a pull request if I have more time.

**Comment by regebro** [comment]
This works with paragraphs, but unfortunately not with lists, but I'm hoping that's just because classes are ignored in the reST.xsl template, which would make it an easy fix.

```
.. class:: substep

    A paragraph

    Another one

    And a third

```

**Comment by pappasam** [comment]
@regebro this works perfectly! I don't think lists are supported in the substeps plugin, so this might be an upstream problem (or simply bad feature removal imho). As far as hovercraft is concerned, I think this issue is closed.

[Substeps documentation](https://github.com/impress/impress.js/tree/master/src/plugins/substep)

**Comment by regebro** [comment]
It still needs to be documented at least, so I'm keeping the issue open for now.

**Comment by regebro** [comment]
This will work in the next release as well:

Unordered list:

```
* Bullet item 1
    .. class:: substep
* Bullet item 2
    .. class:: substep
* Bullet item 3
    .. class:: substep
```

Ordered list:

```
1. Bullet item 1
    .. class:: substep
1. Bullet item 2
    .. class:: substep
1. Bullet item 3
    .. class:: substep
```

Not the most elegant solution, but it'll do for now.

**Comment by regebro** [comment]
Docs added, closed.
