### ISSUE TITLE
Why my font different with the demo version?

### ISSUE THREAD

**Issue by asamsulfat** [regebro/hovercraft#156]
Im already have font folder with this file 
/srv/http/hovercraft/outdir/fonts/texgyreschola-regular-webfont.woff
/srv/http/hovercraft/outdir/fonts/texgyreschola-regular-webfont.ttf
/srv/http/hovercraft/outdir/fonts/texgyreschola-regular-webfont.svg
/srv/http/hovercraft/outdir/fonts/texgyreschola-regular-webfont.eot

but still font not change, how to set the font?

**Comment by regebro** [comment]
This is a css/html issue, really. The fact that the files end up in your out directory should mean that your cdd font definitions are OK, at least.
