### ISSUE TITLE
How to scale images?

### ISSUE THREAD

**Issue by vonpupp** [regebro/hovercraft#158]
Hello,

I would like to include an image on a slide but resize the image. I would like that to be automatically adjusted on both desktop and mobile as happens with text. I am using the following:

```
text                                                                                                                                                                           
====
.. image:: img/test.jpg                                                                                                                                                   
   :height: 720px                                                                                                                                                                             
   :width: 469px                                                                                                                                                                              
   :scale: 50%                                                                                                                                                                                
   :align: center
```

From what I read [here], I need to especify height and width however the image is not being scaled. What am I doing wrong?

[here]: http://docutils.sourceforge.net/docs/ref/rst/directives.html#image

Thank you very much!

**Comment by regebro** [comment]
Impress.js generally scales the view to the available space, so if it works on big screens it works on small screens, so you can just set the width in pixels to whatever works. The height will be scaled automatically unless you specify it.

**Comment by regebro** [comment]
The height and width you specify is not the height and width of the image file, but how large you want it to be scaled. Don't specify both scale and height/width. Generally, just specify the height or width.

**Comment by vonpupp** [comment]
Awesome, now I got it. Thank you very much @regebro!
