### ISSUE TITLE
Can't emphasize lines in a code block

### ISSUE THREAD

**Issue by pvcraven** [regebro/hovercraft#160]
Tried to use restructured text to emphasize some code lines for a presentation. That generated an error.

    .. code-block:: python
        :emphasize-lines: 1,8,13

**Comment by regebro** [comment]
You are correct.

**Comment by pvcraven** [comment]
Can't do `:linenos:` either. Darn, these two features would really make my presentation.

**Comment by regebro** [comment]
Yeah, sorry, it's not a documentation publishing software.
Here's one way of emphasizing different lines: http://slides.regebro.nu/DjangoConEU-2013/#/step-17
Source code:
https://github.com/regebro/prehistoric-python/releases/tag/djangocon2013

I also saw someone having different lines on different slides, and using a zoom effect on the line he wanted to focus on, that looked awesome.

**Comment by regebro** [comment]
There is also https://github.com/nyergler/hieroglyph
