### ISSUE TITLE
Making charts

### ISSUE THREAD

**Issue by tailhook** [regebro/hovercraft#164]
Do anybody knows a good way to make a nice charts when using hovercraft?

Something like this, would be great:

```
.. bar-chart::

  label1: 10
  label2: 20
```

.. that would make a simple svg with bars and scales

But I'm not sure is there any such tool or is it easy/hard to make?

**Comment by regebro** [comment]
That would be very hard to make. You can of course just generate a chart in whatever tool and include it as an image. Embedding dynamic chart tools like Google charts or chart.js might be doable as well, but I don't know exactly how.
