### ISSUE TITLE
Can't reproduce demo

### ISSUE THREAD

**Issue by richardgmorris** [regebro/hovercraft#165]
Sorry if my level of sophistication is not as high as others, but I am struggling to reproduce visual aspects of the [demo](http://regebro.github.io/hovercraft/#/step-1).

Trivally running
`hovercraft hovercraft.rst`

gives terminal output
```
127.0.0.1 - - [21/May/2018 16:33:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2018 16:33:45] "GET /css/hovercraft.css HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2018 16:33:45] "GET /css/impressConsole.css HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2018 16:33:45] "GET /css/highlight.css HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2018 16:33:45] "GET /hovercraft.css HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2018 16:33:45] "GET /js/impress.js HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2018 16:33:45] "GET /js/impressConsole.js HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2018 16:33:45] "GET /js/hovercraft.js HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2018 16:33:45] "GET /images/hovercraft_logo.png HTTP/1.1" 200
```

Yet the presentation renders in the browser's default font, and presumably size (much reduced). Also, it fails to render the image "hovercraft_logo.png". (The relevant files are where they should be).

Perhaps I am being an idiot.  Any help would be much appreciated.  (I am using Ubuntu 16.04 and installed hovercraft via pip3, as recommended).

**Comment by regebro** [comment]
It looks correct. What browser and version is it?

**Comment by regebro** [comment]
Yeah, same versions here, and it works for me.
The fonts are downloaded from google in the demo, so that could conceivably fail, but since you can't load images/hovercraft_logo.png I don't think that's the problem.

So I don't have a good guess of what is going on here. You are clearly loading it correctly, I can see that from the output.

**Comment by richardgmorris** [comment]
Yeah, agreed, thanks for responding anyway.  The only thing that is perhaps worth mentioning is that I had to first install both Python3 and pip3 (via apt-get) since I normally use Anaconda.  The pip3 install put everything in .local, which was unusual I thought, but as I said, I don't have much experience with pip3.  Anyway after adding to $PATH, it *seemed* that everything was working okay...

**Comment by regebro** [comment]
Yeah, Hovercraft starts, and the browser seems to load the css file, it's just ignoring it, which is strange.

**Comment by ccamara** [comment]
I am having the same issue here on kubuntu 18.04, installed hovercrapt using pip3 (actually `pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)`), Firefox 61.0.1 

My output after running `hovercraft tutorial.rst` is the following one:

```

Serving HTTP on 0.0.0.0 port 8000 ...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carlinux/.local/lib/python3.6/site-packages/hovercraft/__init__.py", line 45, in generate_and_observe
    monitor_list = generate(args)
  File "/home/carlinux/.local/lib/python3.6/site-packages/hovercraft/generate.py", line 176, in generate
    source_files.update(template_info.copy_resources(args.targetdir))
  File "/home/carlinux/.local/lib/python3.6/site-packages/hovercraft/template.py", line 179, in copy_resources
    yield from self.copy_resource(resource, targetdir)
  File "/home/carlinux/.local/lib/python3.6/site-packages/hovercraft/template.py", line 162, in copy_resource
    yield self._copy_file(source_path, target_path)
  File "/home/carlinux/.local/lib/python3.6/site-packages/hovercraft/template.py", line 174, in _copy_file
    shutil.copy2(source_path, target_path)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tutorial.css'
```
Same happens if I specify a target directory or try with all the other demos.

I could not understand how did @richardgmorris  fixed the problem on previous comment .

**Comment by richardgmorris** [comment]
Hi @ccamara, I'm afraid I resolved the issue by simply removing everything and starting again!  Although in my case, `tutorial.css' was at least being loaded, which doesn't seem to be true for you?

**Comment by ccamara** [comment]
Oh, my bad: my mistake was way too basic: I had a misspelling on the css file.

**Comment by regebro** [comment]
Happens to everyone.

**Comment by ccamara** [comment]
Hehehe... if @richardgmorris made it work and I did it as well, this issue may be closed :wink:
