### ISSUE TITLE
a new, empty line...

### ISSUE THREAD

**Issue by srhuels** [regebro/hovercraft#169]
sorry, maybe I'm a little bit stupid.
How can i put in a hard linebreak and/or an empty line?

I didn't find in in "read the docs"!

Thanks
Sven

**Comment by regebro** [comment]
Neither restructured text nor HTML have the concept of empty lines, so it depends on what you want to do. Maybe you are looking for something like this?

http://docutils.sourceforge.net/docs/user/rst/quickref.html#line-blocks

**Comment by frederikmoellers** [comment]
If you need to put explicit linebreaks somewhere where line blocks don't work (e.g. inside bullets, enumeration items or headings) , you can also put this in the preamble of your slide deck:

    .. |br| raw:: html
    
      <br />

and then use `|br|` wherever you need an explicit linebreak, e.g. like this:

    This is a heading |br| spanning 2 lines
    =======================================

    * Text bullet 1

    * Text bullet 2 |br| spanning 3 lines |br| and thus keeping the indentation

**Comment by regebro** [comment]
Thanks!
