### ISSUE TITLE
Add a class to slide

### ISSUE THREAD

**Issue by ccamara** [regebro/hovercraft#171]
According to [this section on the documentation](https://hovercraft.readthedocs.io/en/latest/presentations.html#styling-a-specific-slide) currently, it is possible to add a custom id per slide type, which is great.
However, since Id should be unique, I would like to add a custom class so I can share the same css rules in different slides, without having to alter the css every time I make a new presentation.

Would it be possible to add a new field and make it work in a similar way that ids work? 
Eg:
```
:id: Home
:class: title
```
should output something like:

```
<div id="Home" class="step step-level-1 past prev title" ... >
```

**Comment by regebro** [comment]
It's not only possible, that's exactly how it works. :-)

**Comment by ccamara** [comment]
Great! I since I didn't see it on the documentation I thought it was not working.

**Comment by ccamara** [comment]
I've tested and works great! I have created a PR with instructions on the documentation: #172
