### ISSUE TITLE
Incremental bullets

### ISSUE THREAD

**Issue by ccamara** [regebro/hovercraft#173]
`Impress.js` supports incremental bullets and effects (such as fade in, fade out...), but haven't been able to figure out how to achieve that with hovercraft.

**Comment by frederikmoellers** [comment]
Do you mean showing one bullet after another on a slide using the `substep` plugin of impress.js?
That is documented [here](https://hovercraft.readthedocs.io/en/latest/presentations.html#showing-lists-item-by-item). It doesn't go into detail how to get different effects, but that should be the easier step from there.

**Comment by yeyeto2788** [comment]
@ccamara have tried out what @frederikmoellers commented? Just asking for an update in order to close issues 😋 

Or is your issue still persisting?

**Comment by ccamara** [comment]
Hi @yeyeto2788 , thanks for cleaning the issue list. I honestly gave up using hovercraft / impress. Hopefully, with your help and others' you can boost this project and make it even better.

**Comment by regebro** [comment]
Yeah, thanks!
