### ISSUE TITLE
how to use table in hovercraft

### ISSUE THREAD

**Issue by wuyongyi** [regebro/hovercraft#177]
I installed hovercraft in my Mac Osx(10.13.6) box and it works fine until now.
However I failed to display table correctly in my presentation. (In sublime text3 previews model it is fine). I am still checking the generated HTML file to find out why...

`
Simple table:

=====  =====  ======
   Inputs     Output
------------  ------
  A      B    A or B
=====  =====  ======
False  False  False
True   False  True
False  True   True
True   True   True
=====  =====  ======
`

**Comment by regebro** [comment]
This source:

```
----

Works for me
============


=====  =====  ======
   Inputs     Output
------------  ------
  A      B    A or B
=====  =====  ======
False  False  False
True   False  True
False  True   True
True   True   True
=====  =====  ======
```

Works for me. 

The resulting output is a table that seems correct to me:

```
<h1 id="works-for-me">Works for me</h1>
<table cellpadding="0" cellspacing="0"><thead><tr><th colspan="2"><p>Inputs</p></th><th><p>
Output</p></th></tr><tr><th><p>A</p></th><th><p>B</p></th><th><p>A or B</p></th></tr></thead><tbody><tr><td><p>False</p></td><td><p>False</p></td><td><p>False</p></td></tr><tr><t
d><p>True</p></td><td><p>False</p></td><td><p>True</p></td></tr><tr><td><p>False</p></td><td><p>True</p></td><td><p>True</p></td></tr><tr><td><p>True</p></td><td><p>True</p></td>
<td><p>True</p></td></tr></tbody></table>
```

**Comment by wuyongyi** [comment]
Thanks for the message. It seems that it is a problem in the CSS file I am using.  I will try to find a way to solve that.
