### ISSUE TITLE
Any videos showing how to install and use this?

### ISSUE THREAD

**Issue by X3msnake** [regebro/hovercraft#188]
It's not easy to search it on Youtube all i get is the vehicle not the tool

Has anyone made and shared a video a tutorial on for example installing and doing the demo?

**Comment by BracketMaster** [comment]
The is a tutorial.rst [here](https://raw.githubusercontent.com/regebro/hovercraft/master/docs/examples/tutorial.rst). I don't think this page was linked correctly however. I might make a pull request to fix this.

**Comment by yeyeto2788** [comment]
@X3msnake @BracketMaster the [link](https://hovercraft.readthedocs.io/en/latest/) is actually working.

Here you have a [video](https://youtu.be/I63I8Az24d8) showing how to install it via cmd in windows, on linux is similar the installation.

I'll try to make more video as soon as I can but I guess we can close this issue seems it not actually a bug/feature.

**Comment by regebro** [comment]
Cool, cool. Now we have to think about how to integrate this in the docs. We could start with listing videos in the README?

**Comment by yeyeto2788** [comment]
@regebro I'll do it once I do more videos (hopefully next week) if you want I can add it to the README once I have at least installation and basic usage recorded and uploaded to YouTube.

Sounds good for you? If so assign the ticket to me and I'll take care of it.

**Comment by yeyeto2788** [comment]
@regebro can you please take a look at this [video](https://youtu.be/9T744C-hesc) I hope it's ok but I'm not sure if it's ok going with simple here.

**Comment by yeyeto2788** [comment]
Last [video](https://youtu.be/tHSJLF9OnKQ) installing it on Ubuntu. I guess those are the most useful now. I'll proceed with adding them into the README.

**Comment by yeyeto2788** [comment]
I guess we can close this issue now since installation process is explained on readme.
