### ISSUE TITLE
Release version 2.7?

### ISSUE THREAD

**Issue by pappasam** [regebro/hovercraft#191]
@regebro Any updates regarding when you're planning on releasing version 2.7? I'm really excited for the substep plugin (use it sparingly, but effectively) and look forward to the day when I don't need to rely on the github master to use it.

Thanks for your work on this tool! I've used it for a ton of presentations; my colleagues and I love it.

**Comment by regebro** [comment]
I ran out of time, unfortunately, there are a few more things that didn't quite work as I wanted them to after the impress.js upgrade. Hopefully I'll have time soon again.

**Comment by regebro** [comment]
I didn't have much more time, so I released it as beta, and we'll see.
