### ISSUE TITLE
Anchors and other html things

### ISSUE THREAD

**Issue by c0ntradicti0n** [regebro/hovercraft#194]
Hey, 

is there a simple possibility to use normal html formatting or to create blocks, that can be formatted with css? I wonder why it is neither possible to use the rst-syntax to create a link nor a way to to something like this in html. Do you have a suggestion, how to solve that? If not, I say that as a feature request :)

Regards

**Comment by yeyeto2788** [comment]
Hey @c0ntradicti0n, I might be misunderstanding your comment. Can you please, elaborate a bit more on you issue/request? 

As far as I know you can have hyperlinks on the `rst` files.

Regards.
