### ISSUE TITLE
[Suggestion] Add ability to add HTML directly

### ISSUE THREAD

**Issue by Snackomat** [regebro/hovercraft#209]
Hiya!
I've often found myself struggling with not being able to add a specific HTML tag in Hovercraft, depending on the situation. I suggest to add a `.. html::` tag for HTML that Hovercraft straightup copy-pastes. If someone would point me in the right direction in the code I could add that myself.

**Comment by regebro** [comment]
`..raw:: html` should do it.

**Comment by Snackomat** [comment]
<3
