### ISSUE TITLE
Is it possible to use SVG as dynamic background?

### ISSUE THREAD

**Issue by LazyGeniusMan** [regebro/hovercraft#216]
Hi, sorry if the title is confusing, I dont know what it's called. I have abstract SVG image. What I mean by dynamic background is background that will follow slides/step positition so it will create dynamic background effect since when changing slide it will change postition and rotation. It's like [Sozi](https://github.com/senshu/Sozi), but instead of edit it manually in vector image editor and capture position for each frame by order, It's use impress.js and hovercraft for auto positioning.

I tried to change `body` background with SVG image but it give me static background (the SVG is stretch/fill the page). I dont know if this is relevant or not but I read something called SVG Path in docs and `positions.rst` but I don't really understand how that's work or the use of that thing. Is it relevant with what I want to achieve ?

**Comment by regebro** [comment]
Yes, everything, unless specifically given a dynamic position with css, will stay where it's put, and rotate with everything else. 

I would think it's best to put it in the header section. See https://github.com/regebro/hovercraft/blob/master/docs/presentations.rst#adding-headers-and-footers
