### ISSUE TITLE
Positioning relative to other slide.

### ISSUE THREAD

**Issue by tailhook** [regebro/hovercraft#51]
Sometimes it's useful to return back to some slide and then for example change direction of the movement. As an example you can look how reveal.js does that.

So it would be nice to specify position relative to some other slide:

```
:id: central_slide
----
...
----
:data-x: central_slide+1234
```

What do you think?

**Comment by naraesk** [comment]
in the meantime version 2.1 has been released but it seems this is still not possible, isn't it? Would be a great improvement!

**Comment by regebro** [comment]
Yeah, but I haven't had time to implement any new features, sorry.

**Comment by naraesk** [comment]
I see, but  the project is still maintained, isn't it? Would be a great loss if the projects is dying. 

Anyway, I implemented the feature just as described in the first post. Only references to earlier slides are supported, so no cycling can happen. I'm going to make the pull request later today. However, usually I'm working with java/c++ and I'm not very experienced with python. Would be great if you could have a look at my code

**Comment by regebro** [comment]
Make a pull request and I'll look at it!

**Comment by regebro** [comment]
Merged.
