### ISSUE TITLE
Class and id for images

### ISSUE THREAD

**Issue by sajo712** [regebro/hovercraft#60]
I was trying to set a class for an image, but I couldn't get it to work. I'm new to RST, so this is the code I figured out from the docs:

    .. image:: img/img.jpg
        :class: myclass

The output creates the image, but the class attribute is missing. What am I doing wrong? I could successfully set the class attribute on a paragraph, but not on an image...

**Comment by regebro** [comment]
This was a bug, which was fixed in the beta of 2.0. I think you may need to install it explicitly, with `pip install hovercraft==2.0b2`.

**Comment by sajo712** [comment]
I installed 2.0b1 (b2 was a non-existent version according to pip), and the fix worked. Thanks!
