### ISSUE TITLE
Template for jmpress.js

### ISSUE THREAD

**Issue by sajo712** [regebro/hovercraft#61]
Any chance for a jmpress.js template? It's meant to be compatible with impress.js markup, only it has some nice extras, like animated substeps governed by the data-jmpress attribute.

I have checked how a switch to jmpress.js would affect the presentation, and apparently, it broke the console and the help screen, but the rest of the presentation worked fine.

**Comment by regebro** [comment]
I tried out jmpress, and it couldn't render things properly on my Firefox, so I dropped my investigations after that. 

You can make a template yourself using jmpress, but as you noticed the console won't work. So the console need to be modified. I don't know if I can keep compatibility with impress.js. I think it makes more sense to just switch to jmpress.js, but I think it needs to be more stable before I do that.

**Comment by sajo712** [comment]
I see. Well, impress.js doesn't work on Android Chrome, while jmpress.js does, so it's a tradeoff either way. Is it possible to get hovercraft to parse a `:data-jmpress:` attribute in the same way as `:class:` from the .rst files? If that is possible and you gave me a hint where to start, I might try to tinker with it a little bit. Thanks, anyway.

**Comment by regebro** [comment]
jmpress.js still seems unstable on Firefox, which is a bigger issue than impress.js doesn't work on Android Chrome. It's presenter console also sucks.

At the same time impress.js is maintained again, so I'm sticking with impress.js for the time being,
