### ISSUE TITLE
Making hovercraft work as a web based presentation system

### ISSUE THREAD

**Issue by zeigerpuppy** [regebro/hovercraft#62]
Just thought I'd share my experience with setting up an automated build for hovercraft with a web editor.
It works well as a full web-based presentation system.

Firstly, I set up hovercraft on my server

Secondly, I installed codiad on the same server
It's a web-based editor for code that allows editing the hovercraft .rst and .css in a browser
http://codiad.com/

Make sure your permissions are good 
- set ownership for .rst and .css files as www-data so that codiad can edit them
- set the build directory as owned by hovercraft user

Set up a cron job to autobuild every minute
as hover user:
```
crontab -e

SHELL=/bin/bash
* * * * * source /opt/hover/.virtualenvs/env/bin/activate && cd /var/www/codiad/workspace/hovercraft/presentation && hovercraft presentation.rst output > /dev/null
```

Then you can edit your presentation using a web interface and have it built automatically as you go.
It would probably be good to script this a bit further and check for file changes so that there is no build process if the .rst has not changed

**Comment by zeigerpuppy** [comment]
looks like incron my be a good solution to building on file changes
https://www.debian-administration.org/article/581/Running_programs_when_filesystem_events_occur

**Comment by regebro** [comment]
There is in 2.0b1 also a server mode, which will automatically regenerate the files if the source files has changed. That could possibly be used for this. I would not use the built-in server to server the files publically though.
