### ISSUE TITLE
Including SVG images

### ISSUE THREAD

**Issue by zeigerpuppy** [regebro/hovercraft#63]
Is it possible to include SVG images in the presentations?
This would be really useful, especially if it also allowed SVG animations to be embedded.

This is possible in sozi, for instance
http://sozi.baierouge.fr/

**Comment by zeigerpuppy** [comment]
actually my error, this already works, great!
The SVG animation timing is much better rendered in Safari than either Chromium or Firefox, interesting.

**Comment by regebro** [comment]
Cool!
