### ISSUE TITLE
html links not rendering in presentation

### ISSUE THREAD

**Issue by zeigerpuppy** [regebro/hovercraft#64]
I have tried including html links in my slide but they are not rendered:

e.g.
```
Test Slide
==========

test html links

.. _pygments: http://pygments.org/

```

When hovercraft creates the presentation, the link is missing from the presentation, i.e.
```
<div class="step step-level-1" step="2" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-scale="1" data-x="3200" data-y="0" data-z="0"><h1 id="test-slide">Test Slide</h1><p>test html links</p></div></div>
```

I have also tried rendering the tutorial.rst (which has a hyperlink) and it does not get included either,
there are no errors on compiling the presentation

found that the following does produce proper links, is this just a syntax issue on my part or an actual problem?
```
Python_ is `my favourite
programming language`__.

.. _Python: http://www.python.org/

__ Python_ 
```

**Comment by regebro** [comment]
That's weird. The Hyperlink in the tutorial definitely works for me. It's not highlighted in any color though, which is the fault of the CSS.
