### ISSUE TITLE
Image not centered when resized

### ISSUE THREAD

**Issue by crouti** [regebro/hovercraft#67]
I resize my original image (just width) in order to make it fit on my slide, but unfortunately, even with center tag, the image is not centered on the page.
![capture d ecran 2015-02-04 a 15 11 09](https://cloud.githubusercontent.com/assets/10502063/6041844/471bd35c-ac80-11e4-9325-6f1aea86e8b8.png)

**Comment by regebro** [comment]
Urgl! :-)

Anyway, that's like an effect of your CSS and everything, could you provide
a copy of the presentation, so I can investigate?

**Comment by regebro** [comment]
The reason it isn't centered here is that the div.step is set to 800px width. So with images that are bigger, it will end up not centered.

800px is a good value for the typical presentation case, as it's usually done on a projector that has 1024x768 resolution. 800px then leaves 112px in margin on both sides. You can easily override this in your own style sheet if you are using Hovercraft in another setting, or you know that the resolution will be something else. If you want to use 1024x768 as resolution, but you don't want a margin, then set .step { width: 1024px }; in your style sheet.
