### ISSUE TITLE
installation problems on raspberry pi

### ISSUE THREAD

**Issue by nnako** [regebro/hovercraft#68]
Hi,

this might be a bit off-toppic as it doesn't seem to have anything to do with the usage of this promising piece of software. It concerns the installation procedure necessary to run this tool on a minimalistic linux computer (don't have a fully grown ubuntu machine).

After installing libxml2-dev, pip3, python3 (in parallel to python2) and some other packages, the installation procedure still does not run through successfully, regardless of how I try to start installation. Using pip or installing using the setup.py way...

e.g. **sudo pip3 install hovercraft** gives the following output (sorry for its length. Hopefully you see some hints):

	pi@RaspberryPi-02 ~ $ sudo pip3 install hovercraft > prot__pip3_install_hovercraft.txt
	Requirement already satisfied (use --upgrade to upgrade): hovercraft in /usr/local/lib/python3.2/dist-packages/hovercraft-2
	.0b2.dev0-py3.2.egg
	Collecting docutils>=0.9 (from hovercraft)
	  Using cached docutils-0.12.tar.gz
	Collecting lxml>=3.1.0 (from hovercraft)
	  Using cached lxml-3.4.2.tar.gz
		Building lxml version 3.4.2.
		Building without Cython.
		Using build configuration of libxslt 1.1.26
		Building against libxml2/libxslt in the following directory: /usr/lib
		/usr/lib/python3.2/distutils/dist.py:257: UserWarning: Unknown distribution option: 'bugtrack_url'
		  warnings.warn(msg)
	Requirement already satisfied (use --upgrade to upgrade): svg.path in /usr/local/lib/python3.2/dist-packages (from hovercra
	ft)
	Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python3.2/dist-packages/Pygments-2.0.2
	-py3.2.egg (from hovercraft)
	Requirement already satisfied (use --upgrade to upgrade): watchdog in /usr/local/lib/python3.2/dist-packages/watchdog-0.8.3
	-py3.2.egg (from hovercraft)
	Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3/dist-packages (from svg.path->hove
	rcraft)
	Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /usr/local/lib/python3.2/dist-packages (from watc
	hdog->hovercraft)
	Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in /usr/local/lib/python3.2/dist-packages (from watc
	hdog->hovercraft)
	Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /usr/local/lib/python3.2/dist-packages (from
	watchdog->hovercraft)
	Installing collected packages: lxml, docutils
	  Running setup.py install for lxml
		Building lxml version 3.4.2.
		Building without Cython.
		Using build configuration of libxslt 1.1.26
		Building against libxml2/libxslt in the following directory: /usr/lib
		building 'lxml.etree' extension
		gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buf
	fer-size=4 -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-b2k10l/lxml/src/lxml/includes -I/
	usr/include/python3.2mu -c src/lxml/lxml.etree.c -o build/temp.linux-armv6l-3.2/src/lxml/lxml.etree.o -w
		src/lxml/lxml.etree.c:16:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
		compilation terminated.
		/usr/lib/python3.2/distutils/dist.py:257: UserWarning: Unknown distribution option: 'bugtrack_url'
		  warnings.warn(msg)
		error: command 'gcc' failed with exit status 1
		Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-b2k10l/lxml/setu
	p.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --re
	cord /tmp/pip-4sw_kx-record/install-record.txt --single-version-externally-managed --compile:
		Building lxml version 3.4.2.

		Building without Cython.

		Using build configuration of libxslt 1.1.26

		Building against libxml2/libxslt in the following directory: /usr/lib

		running install

		running build

		running build_py

		creating build

		creating build/lib.linux-armv6l-3.2

		creating build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/_elementpath.py -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/__init__.py -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/builder.py -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/usedoctest.py -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/doctestcompare.py -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/ElementInclude.py -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/pyclasslookup.py -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/sax.py -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/cssselect.py -> build/lib.linux-armv6l-3.2/lxml

		creating build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/__init__.py -> build/lib.linux-armv6l-3.2/lxml/includes

		creating build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/html5parser.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/__init__.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/builder.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/_setmixin.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/usedoctest.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/formfill.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/clean.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/_html5builder.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/defs.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/soupparser.py -> build/lib.linux-armv6l-3.2/lxml/html

		copying src/lxml/html/diff.py -> build/lib.linux-armv6l-3.2/lxml/html

		creating build/lib.linux-armv6l-3.2/lxml/isoschematron

		copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv6l-3.2/lxml/isoschematron

		copying src/lxml/lxml.etree.h -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv6l-3.2/lxml

		copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/config.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/uri.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/tree.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv6l-3.2/lxml/includes

		copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv6l-3.2/lxml/includes

		creating build/lib.linux-armv6l-3.2/lxml/isoschematron/resources

		creating build/lib.linux-armv6l-3.2/lxml/isoschematron/resources/rng

		copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv6l-3.2/lxml/isoschematron/resour
	ces/rng

		creating build/lib.linux-armv6l-3.2/lxml/isoschematron/resources/xsl

		copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv6l-3.2/lxml/isoschematron/resources/
	xsl

		copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv6l-3.2/lxml/isoschematron/resources/
	xsl

		creating build/lib.linux-armv6l-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

		copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv6l-3.2/
	lxml/isoschematron/resources/xsl/iso-schematron-xslt1

		copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.li
	nux-armv6l-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

		copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv6l-3.2/lx
	ml/isoschematron/resources/xsl/iso-schematron-xslt1

		copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv6l-3.2
	/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

		copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv6l-
	3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

		copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv6l-3.2/lxml/isosche
	matron/resources/xsl/iso-schematron-xslt1

		running build_ext

		building 'lxml.etree' extension

		creating build/temp.linux-armv6l-3.2

		creating build/temp.linux-armv6l-3.2/src

		creating build/temp.linux-armv6l-3.2/src/lxml

		gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buf
	fer-size=4 -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-b2k10l/lxml/src/lxml/includes -I/
	usr/include/python3.2mu -c src/lxml/lxml.etree.c -o build/temp.linux-armv6l-3.2/src/lxml/lxml.etree.o -w

		src/lxml/lxml.etree.c:16:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden

		compilation terminated.

		/usr/lib/python3.2/distutils/dist.py:257: UserWarning: Unknown distribution option: 'bugtrack_url'

		  warnings.warn(msg)

		error: command 'gcc' failed with exit status 1

		----------------------------------------
		Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-b2k10l/lxml/setup.py';exec(compile(g
	etattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4sw_kx
	-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-b2k10l
	/lxml

Is there some help available?

Thanks.
nnako

**Comment by regebro** [comment]
Yeah, you don't have the Python development headers installed. I don't know which OS you are running but on Raspbian it think would be

    sudo apt-get install python3-dev

Or something similar.

**Comment by nnako** [comment]
Hi Lennart,

thanks for the helpful hint. Finally, installation ran through. Looking forward to use and maybe contribute.

**Comment by nnako** [comment]
Hi,

again this might be connected to some installation issue?:

First, I created a text file **test.rst** and put in some characters (the behaviour is the same when I copy the text from https://hovercraft.readthedocs.org/en/latest/_sources/examples/tutorial.txt into the text file). Then I start the hovercraft application by typing:

**$ hovercraft test.rst test**

I get the following error output:

	Traceback (most recent call last):
	  File "/usr/local/bin/hovercraft", line 9, in <module>
		load_entry_point('hovercraft==1.1', 'console_scripts', 'hovercraft')()
	  File "/usr/local/lib/python3.2/dist-packages/hovercraft/__init__.py", line 74, in main
		htmldata = rst2html(args.presentation, template_info, args.auto_console, args.skip_help, args.skip_notes)
	  File "/usr/local/lib/python3.2/dist-packages/hovercraft/generate.py", line 26, in rst2html
		xml = rst2xml(rststring)
	  File "/usr/local/lib/python3.2/dist-packages/hovercraft/parse.py", line 60, in rst2xml
		settings_overrides={'syntax_highlight': 'short'})
	  File "/usr/local/lib/python3.2/dist-packages/docutils/core.py", line 414, in publish_string
		enable_exit_status=enable_exit_status)
	  File "/usr/local/lib/python3.2/dist-packages/docutils/core.py", line 657, in publish_programmatically
		pub.set_components(reader_name, parser_name, writer_name)
	  File "/usr/local/lib/python3.2/dist-packages/docutils/core.py", line 96, in set_components
		self.reader.set_parser(parser_name)
	  File "/usr/local/lib/python3.2/dist-packages/docutils/readers/__init__.py", line 63, in set_parser
		parser_class = parsers.get_parser_class(parser_name)
	  File "/usr/local/lib/python3.2/dist-packages/docutils/parsers/__init__.py", line 50, in get_parser_class
		module = __import__(parser_name, globals(), locals(), level=1)
	  File "/usr/local/lib/python3.2/dist-packages/docutils/parsers/rst/__init__.py", line 75, in <module>
		from docutils.parsers.rst import states
	  File "/usr/local/lib/python3.2/dist-packages/docutils/parsers/rst/states.py", line 116, in <module>
		from docutils.parsers.rst import directives, languages, tableparser, roles
	  File "/usr/local/lib/python3.2/dist-packages/docutils/parsers/rst/roles.py", line 78, in <module>
		from docutils.utils.code_analyzer import Lexer, LexerError
	  File "/usr/local/lib/python3.2/dist-packages/docutils/utils/code_analyzer.py", line 12, in <module>
		import pygments
	  File "/usr/local/lib/python3.2/dist-packages/Pygments-2.0.2-py3.2.egg/pygments/__init__.py", line 37, in <module>
		from pygments.util import StringIO, BytesIO
	  File "/usr/local/lib/python3.2/dist-packages/Pygments-2.0.2-py3.2.egg/pygments/util.py", line 226
		return u'[%s-%s]' % (unichr(a), unichr(b))
						^
	SyntaxError: invalid syntax
	pi@RaspberryPi-02 ~/examples/hovercraft__test $

**What could the problem / solution be?**

Thanks

**Comment by regebro** [comment]
It looks like Pygments doesn't run on Python 3.2, you will need Python 3.3 or better.

**Comment by nnako** [comment]
Thanks again, Lennart,

after installing Python3.4, uninstalling hovercraft with pip3.2 and re-installing hovercraft using pip3.4 , everything works fine now from the functional perspective. Just the display speed especially for zooming in/out has potential for improvement. I'll try different browsers and faster machines. There might be a general operation speed issue for displaying such complex transformations, eh?

**Comment by regebro** [comment]
Yes, especially if you do 3D transformations. It has a lot to do with the graphics chip and if you have enough memory and good drivers. If you are using it for presentations most projectors are 1024x768, so you don't need to use higher resolution than that, which can also help.
