### ISSUE TITLE
Add js from the rst file

### ISSUE THREAD

**Issue by ggtools** [regebro/hovercraft#72]
Looking at this [presentation](http://pkoperek.github.io/bytecode-presentation) I was wondering if it would be possible to add a `:js-body:` and `:js-header:` similarly to `:css-*:` in order to add custom scripts without the need of tinkering into the template system.

**Comment by regebro** [comment]
That certainly sounds reasonable.

**Comment by loechel** [comment]
Same here, as talked at the PloneConf 2016 that would be fantastic for JS based Charts for the presentation
