### ISSUE TITLE
Embedding another web-page into hovercraft/RestructedText

### ISSUE THREAD

**Issue by DavidPatShuiFong** [regebro/hovercraft#78]
I could not tell from the documentation, but is it possible to embed another web-page into
a hovercraft presentation?

I am thinking, in particular, of an animated HighCharts graph

e.g. http://www.davidfong.info/HighCharts/examples/scatter/SpurAfrika_BMIZAgeSexDetailed.htm

**Comment by regebro** [comment]
You can include an iframe:

    .. raw:: html

       <iframe src="...">
