### ISSUE TITLE
positions.rst  example fails

### ISSUE THREAD

**Issue by yarko** [regebro/hovercraft#81]
This is as far as I've gotten with this:   from docs/examples,  the output in the repository for positions.rst isn't the same as what seems to now be generated (I think this is the same output for python3.4.3 or 3.5b2).

For example (I inserted newlines - `sed s/</^M</g` - so I could get a useful diff), the following is different in `positions.d/index.html`

```html
-<div class="step step-level-1" step="1" data-x="0" data-y="1000" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" 
data-scale="1" data-z="0">
+<div class="step" step="1" data-x="0" data-y="1000">
 <h1 id="x-y">X &amp; Y
 </h1>
-<p>You don't have to give both X and Y coordinates. They will default to "no
+<p>You don't have to gove both X and Y coordinates. They will default to "no
 differece to the last slide" if not given. As the first slide ends up at
 X=0 and Y=0, the 
 <tt>:data-x: 0
 </tt> above is strictly speaking not necessary.
 </p>
 </div>
-<div class="step step-level-1" step="2" data-x="0" data-y="1000" data-z="0" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-scale="1">
+<div class="step" step="2" data-x="0" data-y="2000">
 <h1 id="automatic-positioning">Automatic positioning
 </h1>
 <p>If you don't set a position, Hovercraft! will position the slide
@@ -54,7 +54,7 @@
 up at X=0 and Y=2000.
 </p>
 </div>
-<div class="step step-level-1" step="3" data-x="0" data-y="1000" data-z="0" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-scale="1">
+<div class="step" step="3" data-x="0" data-y="3000">
 <h1 id="positioning-fields">Positioning fields
 </h1>
 <p>Any field starting with 
@@ -86,13 +86,13 @@
 <p>Let's do some zoom and rotate!
 </p>
 </div>
```

(where `-<div..>` is what is generated by the installed hovercraft, from repo, and `+<div..>` is what is in the contents of `docs/examples/positions.d/index.html`)

Note the difference in the two DATA-Y  sequences:
- the code generates absolute position (mirroring the last setting);
- the example output contains relative positioning (regardless of last setting being absolute);

I'm not sure if this change is intended or not, but two things:

Either it should be documented, and the example corrected,
or it should be reverted to the (arguably) more reasonable previous behavior, with a possible setting to force the current setting (?).

Anyway, I'm just reporting this.

**Comment by yarko** [comment]
Digging in, it looks like this is an artifact of merge #50 - so perhaps a solution would be to update positions.rst (which will force earlier introduction of relative positioning), and generate the examples as part of the doc build process...  something like that...

**Comment by regebro** [comment]
Actually testing the examples would probably be a brilliant idea. I'll look into that.
