### ISSUE TITLE
New parameter for "not step slide" for footer, header and other floating div.

### ISSUE THREAD

**Issue by francxk** [regebro/hovercraft#82]
not step class permits to add floatting div (not geenrated in impress div) so you can add header/footer...
may be a convenient syntaxcould be:
 :class: notstep

**Comment by regebro** [comment]
I think headers and footers are better added in the HTML template.

**Comment by regebro** [comment]
I added support for the .. header:: and .. footer:: features of reStructuredText, they can be used for static immovable content like headers and footers.
