### ISSUE TITLE
position overlay on step2 of positions.rst

### ISSUE THREAD

**Issue by topiaruss** [regebro/hovercraft#93]
Hi Lennart.

Playing the positions.rst tutorial results in a confused overlay of two slides.  
Platform: OSX
Browser: Current Chrome
Hovercraft: I'm using the tutorials from head, with the latest pypi version of hovercraft installed via simple pip3 install.

Ignore the grey overlay on the image...

![image](https://cloud.githubusercontent.com/assets/189785/10664285/fd70749a-78b9-11e5-925c-6faa294148a8.png)

**Comment by regebro** [comment]
Yup, fixed.
