### ISSUE TITLE
Python logos

### ISSUE THREAD

**Issue by danstender** [regebro/hovercraft#99]
For the new Debian package, we've had to remove the Python logo images [1] because the Debian legal team has noted that they are not DFSG free. I've patched to fix the gap, but is it maybe possible to replace them with something else?

DS

[1] docs/examples/images/python-logo-master-v3-TM.png
     hovercraft/tests/test_data/images/python-logo-master-v3-TM.png
     hovercraft/tests/test_data/maximal/images/python-logo-master-v3-TM.png

**Comment by regebro** [comment]
Yeah, shouldn't be a problem.
